spring.application.name=order-service

eureka.instance.hostname=localhost
eureka.client.fetch-registry=false
eureka.client.register-with-eureka=false

spring.datasource.url=jdbc:postgresql://localhost:5432/order
spring.datasource.username=postgres
spring.datasource.password=admin

spring.jpa.hibernate.ddl-auto=update

# admin-service will run on port 8761
server.port=8761